Add iron golem spawn egg
SkriptLang/skript-aliases pull request #109
Opened 2024-01-30 18:08 UTC by TheGallium

Referring to issue #108

2024-01-30 18:12 UTC, sovdeeth requested changes

2024-01-30 18:12 UTC, sovdeeth commented on misc-eggs.sk
> +	([iron] golem [spawn] egg|spawn [iron] golem)¦s = minecraft:spawn_egg {Damage:50}
```suggestion
	([iron] golem [spawn] egg|spawn [iron] golem)¦s = minecraft:iron_golem_spawn_egg
```

2024-01-30 18:13 UTC, sovdeeth commented on misc-eggs.sk
> +	([iron] golem [spawn] egg|spawn [iron] golem)¦s = minecraft:spawn_egg {Damage:50}
You'll also need to add this to the all spawn eggs alias.

2024-01-30 18:18 UTC, Fusezion commented
I'm not sure how I feel about making `iron` optional. as snow golem also exists and if we're missing iron we're likely missing that one

*and let's not talk about `spawn (entity)` even being valid across spawn eggs, this is just innately wrong
![image](https://github.com/SkriptLang/skript-aliases/assets/81952476/07257ce9-7220-4e5e-b0b0-e95b814ae4ba)

2024-01-30 18:20 UTC, sovdeeth commented
> I'm not sure how I feel about making `iron` optional. as snow golem also exists and if we're missing iron we're likely missing that one
> 
> *and let's not talk about `spawn (entity)` even being valid across spawn eggs, this is just innately wrong ![image](https://private-user-images.githubusercontent.com/81952476/300919598-07257ce9-7220-4e5e-b0b0-e95b814ae4ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MzkwNzEsIm5iZiI6MTcwNjYzODc3MSwicGF0aCI6Ii84MTk1MjQ3Ni8zMDA5MTk1OTgtMDcyNTdjZTktNzIyMC00ZTVlLWIwYjAtZTk1YjgxNGFlNGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE4MTkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZmY3ZDU2NTA3N2Y4MWQyZjk5ZDZmYzQyYzdmN2VkZGZlYTQ1ODA3Yjg5NzFiOWUyY2VkNzRhYzdhYmNhMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XsHnD3tU6l5ujzCoCZUCGJxEYu64KIKzS1jH_BfqHRM)

good catch with the iron thing
as far as the second point, i agree, but for a different pr.

2024-01-30 19:02 UTC, TheGallium commented
The `minecraft:iron_golem_spawn_egg` item was added in 1.19.3, using it in 1.19 will not work.
Also, for the making `iron` optional, I think `golem` should be the default but for the snow golem, `snow` would be required.

2024-01-30 19:03 UTC, sovdeeth commented
I would prefer both be required. It's better to be explicit about thing to avoid confusion and future conflicts.

2024-01-30 21:53 UTC, sovdeeth approved these changes

2024-01-30 21:59 UTC, Fusezion approved these changes
At work but from what I can see everything that concerned me is fixed

2024-01-31 04:45 UTC, TheBentoBox submitted a review, later dismissed

2024-01-31 04:47 UTC, TheBentoBox commented on misc-eggs.sk
> +	[snow golem [spawn] egg|spawn snow golem)¦s = minecraft:snow_golem_spawn_egg
Accidentally submitted my approval, but this is wrong -- the first square brace should be the open parentheses. Was this tested?

```suggestion
	(iron golem [spawn] egg|spawn iron golem)¦s = minecraft:iron_golem_spawn_egg
	(snow golem [spawn] egg|spawn snow golem)¦s = minecraft:snow_golem_spawn_egg
```

2024-02-02 02:29 UTC, TheBentoBox approved these changes

2024-02-02 06:50 UTC, aabssmc commented
what about ender dragon & wither

2024-03-01 20:16 UTC, APickledWalrus commented on misc-eggs.sk
> +	(snow golem [spawn] egg|spawn snow golem)¦s = minecraft:snow_golem_spawn_egg
```suggestion
	(snow golem [spawn] egg|spawn snow golem)¦s = minecraft:snow_golem_spawn_egg
	[any] spawn egg¦s = any spawn egg, spawn iron golem, spawn snow golem
```

2024-03-01 20:28 UTC, APickledWalrus approved these changes

2024-03-01 20:28 UTC, merged

2024-03-01 20:29 UTC, APickledWalrus commented
Thanks for this!