Spawn Eggs, Music Discs, Dyes, and more!
SkriptLang/skript-aliases pull request #13
Opened 2018-07-28 02:47 UTC by APickledWalrus

I updated misc.sk and completed some of the TODOs.

+ Added spawn eggs (1.13 + 1.12 & older)
+ Added music discs (1.13 + 1.12 & older)
+ Added fish buckets to buckets section
+ Moved horse armor from combat.sk to misc.sk
+ Fixed iron nuggets and added "any nugget"
+ Various other edits

2018-07-28 03:06 UTC, TheBentoBox requested changes
Looks good overall, just a couple of small comments. Awesome work!

2018-07-28 03:06 UTC, TheBentoBox commented on misc.sk
> +	tropical fish bucket¦s = minecraft:clownfish_bucket
It looks to me, [from the wiki](https://minecraft.gamepedia.com/Bucket_of_Fish#ID), that the ID for this is `tropical_fish_bucket`, not `clownfish_bucket`.

2018-07-28 03:06 UTC, TheBentoBox commented on misc.sk
> +	any bucket = empty bucket, water bucket, lava bucket, milk, tropical fish bucket, cod bucket, pufferfish bucket, salmon bucket
I'd recommend adding a separate `any fish bucket` alias.

2018-07-28 03:22 UTC, APickledWalrus commented
The tropical fish bucket should be right now, and I also added the any fish bucket lien you recommended. Thanks for the quick reply :)

2018-07-29 01:15 UTC, TheBentoBox approved these changes

2018-07-29 01:16 UTC, TheBentoBox commented
Gonna ask for a look from some devs since this is a larger PR, but looks good to me now!

2018-07-29 01:24 UTC, abandonedaccount6235 commented on misc.sk
> +	11-[music ]disc¦s = minecraft:music_disc_11
how about `music disc 11`? (also for the other discs)

2018-07-29 03:09 UTC, APickledWalrus commented on misc.sk
> +	11-[music ]disc¦s = minecraft:music_disc_11
Good idea! I’ll change this soon.

2018-07-29 09:15 UTC, Pikachu920 commented on misc.sk
> +	11-[music ]disc¦s = minecraft:music_disc_11
you can use \ to escape that, just so u know. so:
\\[music\\] (disc|record) 11
becomes
\[music\] (disc|record) 11

2018-07-29 13:27 UTC, APickledWalrus commented on misc.sk
> +	11-[music ]disc¦s = minecraft:music_disc_11
Didn’t know this, thank you!

2018-07-31 22:59 UTC, APickledWalrus commented
I updated music discs and updated nuggets/shulker shells to fix the conflict (nuggets were added in 1.11.1 so they can't be put with shulker shells)

2018-08-01 00:54 UTC, TheBentoBox commented
Good change. I like that the record aliases match the IDs now. 

Awesome contribution, this was a lot of work. Cheers!

2018-08-01 00:54 UTC, merged