Ladders and Layers
SkriptLang/skript-aliases pull request #18
Opened 2018-08-11 15:30 UTC by APickledWalrus

This PR isn't that big but has some features that should be added.

> Directional ladders (1.12 and older)
> Number of layers for snow layers (All versions)

2018-08-13 20:45 UTC, TheBentoBox requested changes
Looks good overall, couple bits of simple feedback.

2018-08-13 20:45 UTC, TheBentoBox commented on decoration.sk
>  	snow layer¦s = minecraft:snow_layer
How about adding a `(1|one) layer snow layer = minecraft:snow_layer {Damage:0}` here? That way they can specifically target a thin snow layer.

Additionally, I don't love the alias name here; "two layer snow layer" seems a bit repetitive. Maybe change it to "thick", such as `two thick snow layer`? Open to opinions.

2018-08-13 20:45 UTC, TheBentoBox commented on decoration.sk
> +	(8|eight) layer snow layer = minecraft:snow_layer[layers=8]
Same as above, maybe use "thick" and add one for a specifically one layer thick one.

2018-08-14 17:30 UTC, APickledWalrus commented
I think both changes are good so I did them both. Should be good now!

2018-08-14 18:14 UTC, TheBentoBox approved these changes

2018-08-14 18:14 UTC, TheBentoBox commented
Looks great, thanks as always!

2018-08-14 18:14 UTC, merged