Update misc.sk
SkriptLang/skript-aliases pull request #74
Opened 2021-11-23 08:25 UTC by Netherpwn

I updated some banner patterns so they will match their vanilla ids

2021-11-23 18:40 UTC, TPGamesNL requested changes
I have a small comment, but good change overall 👍

2021-11-23 18:40 UTC, TPGamesNL commented on misc.sk
> +	skull[ charge] banner pattern¦s = minecraft:skull_banner_pattern
You can make the optional part not include the space, Skript makes sure the single space variant is usable anway:
```suggestion
	flower [charge] banner pattern¦s = minecraft:flower_banner_pattern
	creeper [charge] banner pattern¦s = minecraft:creeper_banner_pattern
	skull [charge] banner pattern¦s = minecraft:skull_banner_pattern
```

2021-11-24 00:23 UTC, Netherpwn commented
> 

Thank you, looks better now.

2021-11-24 19:30 UTC, TPGamesNL approved these changes

2022-01-30 18:50 UTC, merged